// list of all 50 US states in alpha order in array form
export const usaStatesList = [
	{name: 'Alabama', shortName: 'AL'},
	{name: 'Alaska', shortName: 'AK'},
	{name: 'Arizona', shortName: 'AZ'},
	{name: 'Arkansas', shortName: 'AR'},
	{name: 'California', shortName: 'CA'},
	{name: 'Colorado', shortName: 'CO'},
	{name: 'Connecticut', shortName: 'CT'},
	{name: 'Delaware', shortName: 'DE'},
	{name: 'Florida', shortName: 'FL'},
	{name: 'Georgia', shortName: 'GA'},
	{name: 'Hawaii', shortName: 'HI'},
	{name: 'Idaho', shortName: 'ID'},
	{name: 'Illinois', shortName: 'IL'},
];

// leaving it at this for now, maybe add the rest later

	// 'Indiana',
	// 'Iowa',
	// 'Kansas',
	// 'Kentucky',
	// 'Louisiana',
	// 'Maine',
	// 'Maryland',
	// 'Massachusetts',
	// 'Michigan',
	// 'Minnesota',
	// 'Mississippi',
	// 'Missouri',
	// 'Montana',
	// 'Nebraska',
	// 'Nevada',
	// 'New Hampshire',
	// 'New Jersey',
	// 'New Mexico',
	// 'New York',
	// 'North Carolina',
	// 'North Dakota',
	// 'Ohio',
	// 'Oklahoma',
	// 'Oregon',
	// 'Pennsylvania',
	// 'Rhode Island',
	// 'South Carolina',
	// 'South Dakota',
	// 'Tennessee',
	// 'Texas',
	// 'Utah',
	// 'Vermont',
	// 'Virginia',
	// 'Washington',
	// 'West Virginia',
	// 'Wisconsin',
	// 'Wyoming',